server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:multillm
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

llm:
  providers:
    openai:
      api-key: ${OPENAI_API_KEY:dummy}
      model: gpt-4
      max-tokens: 1000
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:dummy}
      model: claude-3-sonnet
    google:
      api-key: ${GOOGLE_API_KEY:dummy}
      model: gemini-pro

websocket:
  endpoint: /ws/chat
